sudo: required
services:
  - docker

before_install:
  - docker build -t saif32/docker-react -f Dockerfile.dev .

script:
  - docker run saif32/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-788556419749"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
